import { Product } from '@/types';

export const mockProducts: Product[] = [
  // HOME - Sodimac
  {
    id: 'home-001',
    name: 'Taladro Percutor Bosch GSB 550',
    description: 'Taladro percutor 550W con velocidad variable y reversa. Ideal para trabajos en concreto y madera.',
    price: 49990,
    currency: 'CLP',
    store: 'Sodimac',
    storeUrl: 'https://sodimac.cl',
    imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['taladro', 'herramienta', 'construcción', 'diy', 'bosch'],
    deliveryDays: 3,
  },
  {
    id: 'home-002',
    name: 'Pintura Látex Blanco Mate 4L',
    description: 'Pintura látex premium para interiores. Acabado mate, lavable y de alta cobertura.',
    price: 24990,
    currency: 'CLP',
    store: 'Sodimac',
    storeUrl: 'https://sodimac.cl',
    imageUrl: 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['pintura', 'látex', 'blanco', 'interior', 'decoración'],
    deliveryDays: 2,
  },
  {
    id: 'home-003',
    name: 'Sofá 3 Cuerpos Japandi Natural',
    description: 'Sofá de 3 cuerpos con estructura de madera de roble y tapiz de lino beige. Estilo Japandi minimalista.',
    price: 599990,
    currency: 'CLP',
    store: 'Falabella',
    storeUrl: 'https://falabella.com',
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['sofá', 'living', 'japandi', 'minimalista', 'madera', 'lino'],
    deliveryDays: 7,
  },
  {
    id: 'home-004',
    name: 'Lámpara de Pie Arco Dorado',
    description: 'Lámpara de pie con brazo arqueado y base de mármol. Pantalla de tela color crema.',
    price: 189990,
    currency: 'CLP',
    store: 'Zara Home',
    storeUrl: 'https://zarahome.com',
    imageUrl: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['lámpara', 'iluminación', 'decoración', 'dorado', 'elegante'],
    deliveryDays: 5,
  },
  {
    id: 'home-005',
    name: 'Alfombra Berber 200x300cm',
    description: 'Alfombra estilo berber en tonos neutros. Tejido a mano con lana natural.',
    price: 299990,
    currency: 'CLP',
    store: 'Zara Home',
    storeUrl: 'https://zarahome.com',
    imageUrl: 'https://images.unsplash.com/photo-1600166898405-da9535204843?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['alfombra', 'berber', 'lana', 'decoración', 'living', 'neutro'],
    deliveryDays: 10,
  },
  {
    id: 'home-006',
    name: 'Mesa de Centro Nogal',
    description: 'Mesa de centro en madera de nogal con acabado natural. Diseño escandinavo con patas cónicas.',
    price: 179990,
    currency: 'CLP',
    store: 'Easy',
    storeUrl: 'https://easy.cl',
    imageUrl: 'https://images.unsplash.com/photo-1533090481720-856c6e3c1fdc?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['mesa', 'centro', 'nogal', 'escandinavo', 'living', 'madera'],
    deliveryDays: 5,
  },
  {
    id: 'home-007',
    name: 'Set de Cojines Decorativos x4',
    description: 'Set de 4 cojines decorativos en tonos tierra. Incluye fundas de lino y algodón.',
    price: 59990,
    currency: 'CLP',
    store: 'Zara Home',
    storeUrl: 'https://zarahome.com',
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['cojines', 'decoración', 'textil', 'living', 'tierra'],
    deliveryDays: 3,
  },
  {
    id: 'home-008',
    name: 'Estante Flotante Roble 120cm',
    description: 'Estante flotante de roble macizo con sistema de montaje invisible. Acabado natural.',
    price: 45990,
    currency: 'CLP',
    store: 'Sodimac',
    storeUrl: 'https://sodimac.cl',
    imageUrl: 'https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&h=400&fit=crop',
    category: 'home',
    tags: ['estante', 'flotante', 'roble', 'almacenamiento', 'pared'],
    deliveryDays: 4,
  },

  // FASHION - Zara, H&M, Adidas
  {
    id: 'fashion-001',
    name: 'Chaqueta Cuero Negro Biker',
    description: 'Chaqueta de cuero genuino estilo biker. Cierre asimétrico y detalles metálicos.',
    price: 249990,
    currency: 'CLP',
    store: 'Zara',
    storeUrl: 'https://zara.com',
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['chaqueta', 'cuero', 'negro', 'biker', 'moda'],
    deliveryDays: 4,
  },
  {
    id: 'fashion-002',
    name: 'Zapatillas Blancas Stan Smith',
    description: 'Zapatillas clásicas Adidas Stan Smith en cuero blanco con detalles verdes.',
    price: 89990,
    currency: 'CLP',
    store: 'Adidas',
    storeUrl: 'https://adidas.cl',
    imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['zapatillas', 'blancas', 'adidas', 'stan smith', 'casual'],
    deliveryDays: 3,
  },
  {
    id: 'fashion-003',
    name: 'Pantalón Lino Beige Wide Leg',
    description: 'Pantalón de lino 100% en corte wide leg. Cintura alta con pinzas.',
    price: 45990,
    currency: 'CLP',
    store: 'H&M',
    storeUrl: 'https://hm.com',
    imageUrl: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['pantalón', 'lino', 'beige', 'wide leg', 'verano'],
    deliveryDays: 5,
  },
  {
    id: 'fashion-004',
    name: 'Camisa Oxford Blanca',
    description: 'Camisa Oxford de algodón en blanco clásico. Corte regular fit.',
    price: 34990,
    currency: 'CLP',
    store: 'Zara',
    storeUrl: 'https://zara.com',
    imageUrl: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['camisa', 'oxford', 'blanca', 'formal', 'algodón'],
    deliveryDays: 3,
  },
  {
    id: 'fashion-005',
    name: 'Vestido Midi Negro Satinado',
    description: 'Vestido midi en satén negro con escote en V y espalda descubierta.',
    price: 69990,
    currency: 'CLP',
    store: 'Zara',
    storeUrl: 'https://zara.com',
    imageUrl: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['vestido', 'negro', 'satén', 'elegante', 'fiesta'],
    deliveryDays: 4,
  },
  {
    id: 'fashion-006',
    name: 'Blazer Oversize Gris',
    description: 'Blazer oversize en mezcla de lana gris. Solapas anchas y hombros estructurados.',
    price: 129990,
    currency: 'CLP',
    store: 'H&M',
    storeUrl: 'https://hm.com',
    imageUrl: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['blazer', 'oversize', 'gris', 'formal', 'oficina'],
    deliveryDays: 5,
  },
  {
    id: 'fashion-007',
    name: 'Jeans Straight Azul Oscuro',
    description: 'Jeans de corte recto en denim azul oscuro. Cintura alta, 100% algodón.',
    price: 49990,
    currency: 'CLP',
    store: 'Zara',
    storeUrl: 'https://zara.com',
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['jeans', 'denim', 'azul', 'straight', 'casual'],
    deliveryDays: 3,
  },
  {
    id: 'fashion-008',
    name: 'Polera Básica Negra Pack x3',
    description: 'Pack de 3 poleras básicas de algodón en negro. Cuello redondo, corte regular.',
    price: 29990,
    currency: 'CLP',
    store: 'H&M',
    storeUrl: 'https://hm.com',
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['polera', 'básica', 'negro', 'algodón', 'pack'],
    deliveryDays: 3,
  },
  {
    id: 'fashion-009',
    name: 'Zapatillas Running Ultraboost',
    description: 'Zapatillas de running Adidas Ultraboost con tecnología Boost. Negro con suela blanca.',
    price: 179990,
    currency: 'CLP',
    store: 'Adidas',
    storeUrl: 'https://adidas.cl',
    imageUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['zapatillas', 'running', 'adidas', 'ultraboost', 'deportivo'],
    deliveryDays: 4,
  },
  {
    id: 'fashion-010',
    name: 'Bolso Tote Cuero Camel',
    description: 'Bolso tote en cuero genuino color camel. Amplio interior con bolsillos organizadores.',
    price: 89990,
    currency: 'CLP',
    store: 'Zara',
    storeUrl: 'https://zara.com',
    imageUrl: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop',
    category: 'fashion',
    tags: ['bolso', 'tote', 'cuero', 'camel', 'accesorio'],
    deliveryDays: 4,
  },
];

// Predefined solution templates for common requests
export const solutionTemplates = {
  livingRoom: {
    title: 'Project: Living Room Refresh',
    description: 'Curated selection for a modern, minimalist living space with Japandi influences.',
    roles: ['Main Sofa', 'Accent Lamp', 'Area Rug', 'Coffee Table'],
    productIds: ['home-003', 'home-004', 'home-005', 'home-006'],
  },
  casualOutfit: {
    title: 'Project: Casual Weekend Look',
    description: 'Effortlessly stylish outfit for weekend activities.',
    roles: ['Statement Jacket', 'Classic Sneakers', 'Relaxed Pants', 'Basic Top'],
    productIds: ['fashion-001', 'fashion-002', 'fashion-003', 'fashion-008'],
  },
  officeStyle: {
    title: 'Project: Office Ready',
    description: 'Professional yet modern office attire.',
    roles: ['Structured Blazer', 'Classic Shirt', 'Tailored Jeans', 'Leather Bag'],
    productIds: ['fashion-006', 'fashion-004', 'fashion-007', 'fashion-010'],
  },
  homeImprovement: {
    title: 'Project: DIY Weekend',
    description: 'Essential tools and materials for your home improvement project.',
    roles: ['Power Tool', 'Wall Paint', 'Floating Shelf', 'Decorative Cushions'],
    productIds: ['home-001', 'home-002', 'home-008', 'home-007'],
  },
};

export type SolutionTemplateKey = keyof typeof solutionTemplates;
